version: "3.8"

services:
  frontend:
    build: .
    image: ru0300zaman/myapp3:latest # Replace with your Docker Hub details
    ports:
      - "3000:80"
    depends_on:
      - db

  db:
    image: postgres:13-alpine # Or your preferred database image
    environment:
      POSTGRES_USER: zaman
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data:
